#!/bin/bash 

find ./ -type d -and -not -path "./" > dirs1.txt

mkdir test1

while read line
do
echo $line
\cp -rf $line test1/
done < dirs1.txt

echo "./MainFlask.py" > dirs2.txt

while read line
do
echo $line
\cp -rf $line test1/
done < dirs2.txt


pip install requests
pip install flask
pip install elasticsearch
pip install bs4
pip install nltk
pip install ssl
pip install numpy  

python ./MainFlask.py
